### PR TITLE
Support for translation of system variable

### PR DESCRIPTION
**Pull request by charlymr**
Hello,

great project! I am planning to use, it, but in my case I will need translation to work.

So, I checked out the logic, 

### 1st Added a simple mechanisms to actually give the option to suffix any system variable with the local. 

Exemple:
delete.cancel -> Cancel
delete.cancel.fr -> Effacer
delete.cancel.fr_FR -> Supprimer

The method will pickup the default FR language if you have for exemple, fr_BE as locale, so it would be delete.cancel.fr 
But if you have fr_FR, it will then pick delete.cancel.fr_FR.
Finally there is a fall back in case, the user added only the translated strings, so we can discover them

### 2nd I reviewed some of the templates
This is to better support translation. I am starting only so may come back with some more soon

Thanks for you consideration,

Denis

### CODE REVIEW

**Comment by charlymr** [comment]
@tib oh and by the way, I really like your book. Fantastic project you have here!

**Comment by tib** [comment]
Hi @charlymr,

first of all thank you for your contribution, it's really amazing that you are interested in this project. 😊

You should know that I 100% support implementing localization support, but I want to follow quite a different approach here.

System variables are there for storing generic settings (maybe I did a mistake storing messages there 😅), so I really don't want to mix them up with locales. It would be nice to have a new language / locale / i18n / whatever module and implement this feature independently from other parts of the system. 

We can add a new function / method to the core for translating string values, but I'd avoid using the system scope for this purpose. Then some other module could hook into this Leaf entity and provide translation for a given string value using a locale code or the default language code. This way modules could define their own localizable strings and if the language module is enabled the system could translate everything as expected.

e.g. "edit".localized() 
- The localized method is a LeafEntity 
- Call: let translation: String? = req.hook("localize", args: ["value": "edit", "locale": "hu"])  // fallback if needed
- Lang module implements the localize_hook and translates the string based on a localization file.
- Localization files could be provided with the translation strings using a standard format
- The whole thing could be turned on / off (if someone don't needs it) using the module as an SPM dependency

Would you be interested building something like this? If yes then I'll give you some more help. 🙈

**Comment by charlymr** [comment]
Hi @tib,

I am discovering slowly your framework. Still eating your book, so far I am at Chapter 3 So will need some time before going to a whole module implementation. But yes defo I will be investing time on that! 

Also very new to Vapor which look very promising! I come from the iOS world, but I actually see many avdantages using this approach, for CMS. (Much better than mysql + php) which is what I have been using so far. What I really like here is the idea of having a CMS, then have the API on top of it, so best of 2 worlds, with a web app!

For you approach, yes I think you are right, I did jump a bit into the DB too fast  maybe. 

I'll keep in touch, once I am ready to start implementing a module :) For the moment, I am still playing (discovering) the whole thing! 

Many thanks,

Denis

**Comment by tib** [comment]
Great, sounds good. I am going to write proper docs for Feather, so it's going to be more easy to see how the system is composed together and how you can use the extension points to build new features. 👍

**Pull request closed without merging**
